package jose.junnon.model;
// Generated 30 Oct, 2013 3:53:29 PM by Hibernate Tools 3.2.1.GA



/**
 * Achievement generated by hbm2java
 */
public class Achievement  implements java.io.Serializable {


     private long id;
     private String title;
     private String photo;
     private String description;

    public Achievement() {
    }

	
    public Achievement(long id) {
        this.id = id;
    }
    public Achievement(long id, String title, String photo, String description) {
       this.id = id;
       this.title = title;
       this.photo = photo;
       this.description = description;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


