package jose.junnon.model;
// Generated 30 Oct, 2013 3:53:29 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Album generated by hbm2java
 */
public class Album  implements java.io.Serializable {


     private long id;
     private String title;
     private String photo;
     private Boolean isactive;
     private Set photogalleries = new HashSet(0);

    public Album() {
    }

	
    public Album(long id) {
        this.id = id;
    }
    public Album(long id, String title, String photo, Boolean isactive, Set photogalleries) {
       this.id = id;
       this.title = title;
       this.photo = photo;
       this.isactive = isactive;
       this.photogalleries = photogalleries;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Boolean getisactive() {
        return this.isactive;
    }
    
    public void setisactive(Boolean isactive) {
        this.isactive = isactive;
    }
    public Set getPhotogalleries() {
        return this.photogalleries;
    }
    
    public void setPhotogalleries(Set photogalleries) {
        this.photogalleries = photogalleries;
    }




}


