package jose.junnon.model;
// Generated 30 Oct, 2013 3:53:29 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private long id;
     private String title;
     private Date startdate;
     private Date enddate;
     private String description;
     private String photo;
     private String place;

    public Event() {
    }

	
    public Event(long id) {
        this.id = id;
    }
    public Event(long id, String title, Date startdate, Date enddate, String description, String photo, String place) {
       this.id = id;
       this.title = title;
       this.startdate = startdate;
       this.enddate = enddate;
       this.description = description;
       this.photo = photo;
       this.place = place;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }




}


