package jose.junnon.model;
// Generated 30 Oct, 2013 3:53:29 PM by Hibernate Tools 3.2.1.GA



/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private long id;
     private String name;
     private String photo;
     private String description;
     private String designation;

    public Faculty() {
    }

	
    public Faculty(long id) {
        this.id = id;
    }
    public Faculty(long id, String name, String photo, String description, String designation) {
       this.id = id;
       this.name = name;
       this.photo = photo;
       this.description = description;
       this.designation = designation;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }




}


