package jose.junnon.model;
// Generated 30 Oct, 2013 3:53:29 PM by Hibernate Tools 3.2.1.GA



/**
 * PersonInfo generated by hbm2java
 */
public class PersonInfo  implements java.io.Serializable {


     private long id;
     private String name;
     private String phoneNumber;
     private String emailId;

    public PersonInfo() {
    }

	
    public PersonInfo(long id) {
        this.id = id;
    }
    public PersonInfo(long id, String name, String phoneNumber, String emailId) {
       this.id = id;
       this.name = name;
       this.phoneNumber = phoneNumber;
       this.emailId = emailId;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }




}


