package jose.junnon.model;
// Generated 30 Oct, 2013 3:53:29 PM by Hibernate Tools 3.2.1.GA



/**
 * Photogallery generated by hbm2java
 */
public class Photogallery  implements java.io.Serializable {


     private long id;
     private Album album;
     private String photo;
     private String description;

    public Photogallery() {
    }

	
    public Photogallery(long id) {
        this.id = id;
    }
    public Photogallery(long id, Album album, String photo, String description) {
       this.id = id;
       this.album = album;
       this.photo = photo;
       this.description = description;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Album getAlbum() {
        return this.album;
    }
    
    public void setAlbum(Album album) {
        this.album = album;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


