package jose.junnon.model;
// Generated 30 Oct, 2013 3:53:29 PM by Hibernate Tools 3.2.1.GA



/**
 * Usermain generated by hbm2java
 */
public class Usermain  implements java.io.Serializable {


     private long id;
     private String username;
     private String password1;

    public Usermain() {
    }

    public Usermain(long id, String username, String password1) {
       this.id = id;
       this.username = username;
       this.password1 = password1;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword1() {
        return this.password1;
    }
    
    public void setPassword1(String password1) {
        this.password1 = password1;
    }




}


