package jose.junnon.model;
// Generated 30 Oct, 2013 3:53:29 PM by Hibernate Tools 3.2.1.GA



/**
 * Videogallery generated by hbm2java
 */
public class Videogallery  implements java.io.Serializable {


     private long id;
     private String video;

    public Videogallery() {
    }

	
    public Videogallery(long id) {
        this.id = id;
    }
    public Videogallery(long id, String video) {
       this.id = id;
       this.video = video;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }




}


